execution_env=local
#execution_env=remote

#appURL=http://host.docker.internal/opencart/upload/index.php
appURL=http://localhost/opencart/upload/index.php
#email=admin.a@gmail.com
#password=Random@143
#password=Random@1431


